# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: transfer_app_development

test:
  <<: *default
  database: transfer_app_test

production:
  <<: *default
  database: transfer_app_production
  username: transfer_app
  password: <%= ENV["TRANSFER_APP_DATABASE_PASSWORD"] %>
